#!/usr/bin/env python3
"""Generate Mintlify SDK reference pages from the canonical async Python client."""

from __future__ import annotations

import argparse
import ast
import re
import sys
from dataclasses import dataclass
from pathlib import Path


GENERATED_NOTICE = "{/* Generated by scripts/generate_sdk_reference.py. Do not edit directly. */}"
ENDPOINT_RE = re.compile(r"^(GET|POST|PUT|PATCH|DELETE)\s+``([^`]+)``")
HIDDEN_TRANSPORT_PARAMS = {"client", "headers"}


@dataclass(frozen=True)
class Parameter:
    name: str
    annotation: str
    required: bool
    default: str


@dataclass(frozen=True)
class Method:
    name: str
    parameters: tuple[Parameter, ...]
    returns: str
    docstring: str


@dataclass(frozen=True)
class Resource:
    name: str
    attribute: str
    methods: tuple[Method, ...]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--api-root", type=Path, required=True, help="Path to bevorai-api.")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("sdk-reference/python"),
        help="Directory where generated MDX pages are written.",
    )
    parser.add_argument("--check", action="store_true", help="Fail if generated pages are stale.")
    return parser.parse_args()


def annotation(node: ast.expr | None) -> str:
    return ast.unparse(node) if node is not None else "Any"


def parameters(node: ast.AsyncFunctionDef) -> tuple[Parameter, ...]:
    result: list[Parameter] = []
    positional = [*node.args.posonlyargs, *node.args.args]
    defaults: list[ast.expr | None] = [None] * (len(positional) - len(node.args.defaults)) + list(
        node.args.defaults
    )
    for argument, default in zip(positional, defaults):
        if argument.arg == "self" or argument.arg in HIDDEN_TRANSPORT_PARAMS:
            continue
        result.append(
            Parameter(
                argument.arg,
                annotation(argument.annotation),
                default is None,
                "—" if default is None else ast.unparse(default),
            )
        )
    for argument, default in zip(node.args.kwonlyargs, node.args.kw_defaults):
        if argument.arg in HIDDEN_TRANSPORT_PARAMS:
            continue
        result.append(
            Parameter(
                argument.arg,
                annotation(argument.annotation),
                default is None,
                "—" if default is None else ast.unparse(default),
            )
        )
    return tuple(result)


def parse_resource(path: Path) -> Resource | None:
    tree = ast.parse(path.read_text(), filename=str(path))
    resource_class = next(
        (
            node
            for node in tree.body
            if isinstance(node, ast.ClassDef)
            and node.name.startswith("Security")
            and node.name.endswith("Resources")
            and not node.name.startswith("Bound")
        ),
        None,
    )
    if resource_class is None:
        return None
    methods = tuple(
        Method(
            node.name,
            parameters(node),
            annotation(node.returns),
            ast.get_docstring(node) or "",
        )
        for node in resource_class.body
        if isinstance(node, ast.AsyncFunctionDef) and not node.name.startswith("_")
    )
    # Resource module names match the attributes registered on SecurityClient.
    return Resource(resource_class.name, path.stem, methods)


def table_text(value: str) -> str:
    return " ".join(value.split()).replace("|", "\\|") or "—"


def method_summary(method: Method) -> str:
    endpoint = ENDPOINT_RE.match(method.docstring)
    if endpoint:
        return f"{endpoint.group(1)} `{endpoint.group(2)}`"
    return method.docstring


def usage(resource: Resource, method: Method, *, is_async: bool) -> str:
    required = [parameter.name for parameter in method.parameters if parameter.required]
    prefix = "result = await" if is_async else "result ="
    call = f"{prefix} client.{resource.attribute}.{method.name}"
    if not required:
        return f"{call}()"
    args = "\n".join(f"    {name}={name}," for name in required)
    return f"{call}(\n{args}\n)"


def render_method(resource: Resource, method: Method) -> str:
    lines = [f"## `{method.name}`", "", method_summary(method), ""]
    lines.extend(
        [
            "<CodeGroup>",
            '```python Async',
            usage(resource, method, is_async=True),
            "```",
            "",
            '```python Sync',
            usage(resource, method, is_async=False),
            "```",
            "</CodeGroup>",
            "",
        ]
    )
    if method.parameters:
        lines.extend(
            [
                "| Parameter | Type | Required | Default |",
                "| --- | --- | --- | --- |",
            ]
        )
        for parameter in method.parameters:
            lines.append(
                f"| `{parameter.name}` | `{table_text(parameter.annotation)}` | "
                f"{'Yes' if parameter.required else 'No'} | `{table_text(parameter.default)}` |"
            )
        lines.append("")
    lines.extend([f"**Returns:** `{table_text(method.returns)}`", ""])
    return "\n".join(lines)


def render_resource(resource: Resource) -> str:
    display_name = resource.attribute.title()
    methods = "\n".join(render_method(resource, method) for method in resource.methods)
    return f"""---
title: '{display_name}'
description: 'Python SDK reference for the {resource.attribute} resource'
---

{GENERATED_NOTICE}

<Note>The Bevor SDK is coming soon. This page previews its planned Python interface.</Note>

Access this resource from `client.{resource.attribute}`. Both async and sync clients expose the same methods.

{methods.rstrip()}
"""


def render_overview(resources: list[Resource]) -> str:
    cards = "\n".join(
        f'<Card title="{resource.attribute.title()}" icon="code" '
        f'href="/sdk-reference/python/{resource.attribute}">\n'
        f"  Reference for `client.{resource.attribute}`.\n"
        "</Card>"
        for resource in resources
    )
    return f"""---
title: 'Python SDK'
description: 'Preview the coming-soon Bevor Security Python SDK'
---

{GENERATED_NOTICE}

The Bevor Security SDK provides typed async and sync Python clients for security analyses, findings, remediations, and related workflows.

<Warning>
  The Bevor SDK is coming soon and is not published for installation. This reference previews the planned interface; do not run these examples yet.
</Warning>

## Installation preview

```bash Preview — do not run
# Coming soon; the package is not publicly installable.
# pip install bevor-security-sdk
```

## Client preview

<CodeGroup>
```python Async
from bevor_security_sdk import SecurityClient

async with SecurityClient(api_key="YOUR_API_KEY") as client:
    analyses = await client.analyses.list()
```

```python Sync
from bevor_security_sdk.sync_client import SecurityClient

with SecurityClient(api_key="YOUR_API_KEY") as client:
    analyses = client.analyses.list()
```
</CodeGroup>

## Resources

<CardGroup cols={{2}}>
{cards}
</CardGroup>
"""


def expected_pages(api_root: Path) -> dict[str, str]:
    resource_dir = (
        api_root / "packages" / "security-sdk" / "bevor_security_sdk" / "_async" / "resources"
    )
    if not resource_dir.is_dir():
        raise SystemExit(f"SDK resources not found: {resource_dir}")
    resources = [
        resource
        for path in sorted(resource_dir.glob("*.py"))
        if path.name != "__init__.py" and (resource := parse_resource(path)) is not None
    ]
    return {
        "overview.mdx": render_overview(resources),
        **{f"{resource.attribute}.mdx": render_resource(resource) for resource in resources},
    }


def main() -> None:
    args = parse_args()
    pages = expected_pages(args.api_root.resolve())
    output = args.output.resolve()
    existing_generated = {
        path.name
        for path in output.glob("*.mdx")
        if GENERATED_NOTICE in path.read_text()
    }
    stale = sorted(existing_generated - pages.keys())
    changed = [
        name
        for name, content in pages.items()
        if not (output / name).is_file() or (output / name).read_text() != content
    ]
    if args.check:
        if changed or stale:
            names = [*changed, *stale]
            print("SDK reference is stale: " + ", ".join(names), file=sys.stderr)
            raise SystemExit(1)
        print(f"SDK reference is current ({len(pages)} pages).")
        return

    output.mkdir(parents=True, exist_ok=True)
    for name in stale:
        (output / name).unlink()
    for name, content in pages.items():
        (output / name).write_text(content)
    print(f"Generated {len(pages)} SDK reference pages in {output}.")


if __name__ == "__main__":
    main()
