#!/usr/bin/env python3
"""Generate Mintlify CLI reference pages from the Bevor Typer application."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, Iterable


GENERATED_NOTICE = "{/* Generated by scripts/generate_cli_reference.py. Do not edit directly. */}"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--api-root",
        type=Path,
        required=True,
        help="Path to the bevorai-api repository.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("cli-reference"),
        help="Directory where generated MDX pages are written.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the committed reference differs from generated output.",
    )
    return parser.parse_args()


def clean_text(value: Any) -> str:
    if not value:
        return ""
    return " ".join(str(value).strip().split())


def table_text(value: Any) -> str:
    text = clean_text(value).replace("|", "\\|")
    return text or "—"


def yaml_text(value: str) -> str:
    return value.replace("'", "''")


def command_children(command: Any) -> dict[str, Any]:
    """Return child commands without relying on Typer's vendored Click classes."""
    children = getattr(command, "commands", None)
    return dict(children) if children is not None else {}


def command_help(command: Any) -> str:
    return clean_text(getattr(command, "help", None) or getattr(command, "short_help", None))


def is_option(param: Any) -> bool:
    return getattr(param, "param_type_name", None) == "option"


def param_type(param: Any) -> str:
    value_type = getattr(param, "type", None)
    choices = getattr(value_type, "choices", None)
    if choices:
        return " | ".join(str(choice) for choice in choices)
    name = getattr(value_type, "name", None)
    if name and name != "text":
        return str(name)
    return "string"


def param_name(param: Any) -> str:
    options = (
        [*getattr(param, "opts", ()), *getattr(param, "secondary_opts", ())]
        if is_option(param)
        else []
    )
    if options:
        return ", ".join(options)
    return str(getattr(param, "human_readable_name", None) or getattr(param, "name", "argument"))


def param_default(param: Any) -> str:
    if getattr(param, "required", False):
        return "—"
    default = getattr(param, "default", None)
    if callable(default):
        return "dynamic"
    if default is None:
        return "None"
    if isinstance(default, bool):
        return str(default).lower()
    return str(default)


def visible_params(command: Any) -> list[Any]:
    return [param for param in getattr(command, "params", ()) if not getattr(param, "hidden", False)]


def usage(path: str, command: Any) -> str:
    suffix: list[str] = []
    if any(is_option(param) for param in visible_params(command)):
        suffix.append("[OPTIONS]")
    for param in visible_params(command):
        if is_option(param):
            continue
        name = str(getattr(param, "human_readable_name", None) or param.name).upper()
        suffix.append(name if getattr(param, "required", False) else f"[{name}]")
    if command_children(command):
        suffix.append("COMMAND [ARGS]...")
    return " ".join([path, *suffix])


def walk_leaves(command: Any, path: str) -> Iterable[tuple[str, Any]]:
    children = command_children(command)
    if not children:
        yield path, command
        return
    for name, child in children.items():
        yield from walk_leaves(child, f"{path} {name}")


def render_command(path: str, command: Any) -> str:
    lines = [f"## `{path}`", ""]
    help_text = command_help(command)
    if help_text:
        lines.extend([help_text, ""])
    lines.extend(["```bash", usage(path, command), "```", ""])

    params = visible_params(command)
    if params:
        lines.extend(
            [
                "| Parameter | Type | Required | Default | Description |",
                "| --- | --- | --- | --- | --- |",
            ]
        )
        for param in params:
            lines.append(
                "| `{name}` | {kind} | {required} | {default} | {description} |".format(
                    name=table_text(param_name(param)),
                    kind=table_text(param_type(param)),
                    required="Yes" if getattr(param, "required", False) else "No",
                    default=table_text(param_default(param)),
                    description=table_text(getattr(param, "help", None)),
                )
            )
        lines.append("")
    return "\n".join(lines)


def render_page(title: str, description: str, commands: Iterable[tuple[str, Any]]) -> str:
    body = "\n".join(render_command(path, command) for path, command in commands)
    return (
        "---\n"
        f"title: '{yaml_text(title)}'\n"
        f"description: '{yaml_text(description)}'\n"
        "---\n\n"
        f"{GENERATED_NOTICE}\n\n"
        "<Note>The Bevor CLI is coming soon. This page previews its planned command interface.</Note>\n\n"
        f"{description}\n\n"
        f"{body.rstrip()}\n"
    )


def render_overview(groups: list[tuple[str, Any]]) -> str:
    cards = [
        '<Card title="Root commands" icon="terminal" href="/cli-reference/root-commands">\n'
        "  Authentication, initialization, context, and general CLI commands.\n"
        "</Card>"
    ]
    for name, command in groups:
        cards.append(
            f'<Card title="{name.title()}" icon="terminal" href="/cli-reference/{name}">\n'
            f"  {command_help(command) or f'Reference for bevor {name} commands.'}\n"
            "</Card>"
        )
    cards_text = "\n".join(cards)
    return f"""---
title: 'CLI Reference'
description: 'Preview the complete command reference for the coming-soon Bevor CLI'
---

{GENERATED_NOTICE}

The Bevor CLI provides smart contract security analysis and code graph exploration from your terminal.

<Warning>
  The Bevor CLI is coming soon and is not published for installation. This reference previews the planned interface; do not run these commands yet.
</Warning>

## Installation preview

```bash Preview — do not run
# Coming soon; the package is not publicly installable.
# pip install bevor-cli
```

When the CLI launches, its built-in help will provide the same command tree:

```bash Preview — do not run
# bevor --help
```

## Commands

<CardGroup cols={{2}}>
{cards_text}
</CardGroup>
"""


def expected_pages(api_root: Path) -> dict[str, str]:
    cli_package = api_root / "packages" / "cli"
    if not cli_package.is_dir():
        raise SystemExit(f"CLI package not found: {cli_package}")
    sys.path.insert(0, str(cli_package))

    from typer.main import get_command

    from bevor_cli.apps.main import app

    root = get_command(app)
    children = command_children(root)
    groups = [(name, command) for name, command in children.items() if command_children(command)]
    root_commands = [("bevor", root), *[
        (f"bevor {name}", command)
        for name, command in children.items()
        if not command_children(command)
    ]]

    pages = {
        "overview.mdx": render_overview(groups),
        "root-commands.mdx": render_page(
            "Root commands",
            "Authentication, initialization, context, and general Bevor CLI commands.",
            root_commands,
        ),
    }
    for name, command in groups:
        title = f"{name.title()} commands"
        description = command_help(command) or f"Reference for bevor {name} commands."
        pages[f"{name}.mdx"] = render_page(
            title,
            description,
            walk_leaves(command, f"bevor {name}"),
        )
    return pages


def main() -> None:
    args = parse_args()
    pages = expected_pages(args.api_root.resolve())
    output = args.output.resolve()

    existing_generated = {
        path.name
        for path in output.glob("*.mdx")
        if GENERATED_NOTICE in path.read_text()
    }
    stale = sorted(existing_generated - pages.keys())
    changed = [
        name
        for name, content in pages.items()
        if not (output / name).is_file() or (output / name).read_text() != content
    ]
    if args.check:
        if changed or stale:
            names = [*changed, *stale]
            print("CLI reference is stale: " + ", ".join(names), file=sys.stderr)
            raise SystemExit(1)
        print(f"CLI reference is current ({len(pages)} pages).")
        return

    output.mkdir(parents=True, exist_ok=True)
    for name in stale:
        (output / name).unlink()
    for name, content in pages.items():
        (output / name).write_text(content)
    print(f"Generated {len(pages)} CLI reference pages in {output}.")


if __name__ == "__main__":
    main()
